# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'VS2017-Win2016' # other options: 'macOS 10.13', 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
#- task: DotNetCoreInstaller@0
#  inputs:
#    version: '2.1.300' # replace this value with the version that you need for your project

- script: dotnet build ./Apps/PortableLibrary.Apps.TelegramBot --configuration $(buildConfiguration)
  displayName: Build TelegramBot

#- task: DotNetCoreCLI@2
#  displayName: Test
#  inputs:
#    command: test
#    projects: '**/*Tests/*.csproj'
#    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Prepare Artifacts for TelegramBot
  inputs:
    command: publish
    projects: './Apps/PortableLibrary.Apps.TelegramBot'
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/telegram-bot'
    zipAfterPublish: True

# Publish the artifacts
- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts for TelegramBot
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)/telegram-bot
    artifactName: drop
    
#- task: AzureRmWebAppDeployment@3
#  displayName: Publishing to azure
#  inputs:
#    azureSubscription: '<Azure service connection>'
#    WebAppName: '<Name of web app>'
#    Package: $(System.ArtifactsDirectory)/**/*.zip
